name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  push-ghcr:
    uses: genzitizens/ci-templates/.github/workflows/push-to-ghcr.yml@main
    with:
      image_name: code-4-sg
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: push-ghcr
    uses: genzitizens/ci-templates/.github/workflows/deploy-to-vps.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    with:
      IMAGE_NAME: "code-4-sg"
      COMPOSE_PATH: "/home/exeltan/code-4-sg/docker-compose.yml"