name: Deploy My React App

on:
  push:
    branches: [main]

jobs:
  react-ci:
    uses: genzitizens/ci-templates/.github/workflows/react-ci.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  push-ghcr:
    needs: react-ci
    if: needs.react-ci.result == 'success' # react-ci must be successful in order to allow this 
    uses: genzitizens/ci-templates/.github/workflows/push-to-ghcr.yml@main
    with:
      image_name: code-4-sg
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  deploy:
    needs: push-ghcr
    uses: genzitizens/ci-templates/.github/workflows/deploy-to-vps.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
    with:
      IMAGE_NAME: "code-4-sg"
      COMPOSE_PATH: "/home/exeltan/code-4-sg/docker-compose.yml"